# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Amazon project
author: Juliano J Assunção, Lars Peter Hansen, Todd Munson and José A Scheinkman
logo: mfr.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - Amazon.bib


# Information about where the book exists on the web
repository:
  url: https://github.com/lphansen/Amazon/tree/gh-pages  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_css: ["_static/custom.css"]


sphinx:
  config:
    # html_theme : 'piccolo_theme'
    html_theme_options: 
              "show_nav_level": 0 
    # mathjax_macros: book/latexdefs.tex
      # include: 
  # nb_custom_formats:
  #       .sty:
  #           - jupytext.reads
  #           - fmt: sty
  extra_extensions:
  - sphinx_external_toc

# parse:
#   myst_enable_extensions:
#     - amsmath

only_build_toc_files: true